# Generated by Django 5.0.6 on 2024-06-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=10)),
                ('raza', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('tamano', models.CharField(max_length=50)),
                ('url_foto', models.URLField()),
                ('url_detalle', models.URLField()),
            ],
        ),
    ]
